from snakemake.utils import validate

if not config:
    configfile: "../.test/config.yaml"

validate(config, "schemas/config.schema.yaml")

include: "rules/common.smk"
include: "rules/mash_dists.smk"
include: "rules/blocks.smk"
include: "rules/snps.smk"
include: "rules/coordinate_mapping.smk"
include: "rules/dotplots.smk"
include: "rules/run_summary.smk"
include: "rules/block_stats.smk"
include: "rules/region_overview.smk"
include: "rules/kasp.smk"
include: "rules/in_silico_validation.smk"
include: "rules/aggregation.smk"

SNP_DATA_OUTPUTS = [
    BLOCK_COORDINATES_TSV,
    SNP_VCF,
    SNP_POS_LONG_TSV,
    SNP_SUMMARY_TSV,
    DIAGNOSTIC_SNPS_VCF,
]


SNP_TARGET_OUTPUTS = [
    *SNP_DATA_OUTPUTS,
    *get_region_viewer_outputs("snps"),
    DOTPLOT_GALLERY_HTML,
    *DOTPLOT_GALLERY_SVGS,
    *DOTPLOT_VIEWER_SVGS,
    RUN_SUMMARY_TXT,
]


KASP_TARGET_OUTPUTS = [
    *SNP_DATA_OUTPUTS,
    KASP_SUMMARY_TSV,
    CANDIDATE_SNPS_VCF,
    ASSAY_SUMMARY_TSV,
    CANDIDATE_ASSAYS_TSV,
    PRIMERS_TO_ORDER_TSV,
    *get_region_viewer_outputs("kasp"),
    DOTPLOT_GALLERY_HTML,
    *DOTPLOT_GALLERY_SVGS,
    *DOTPLOT_VIEWER_SVGS,
    RUN_SUMMARY_TXT,
]


rule snps:
    default_target: True
    input:
        SNP_TARGET_OUTPUTS

rule kasp:
    input:
        KASP_TARGET_OUTPUTS
