project:
  name: "Test dataset"

inputs:
  genotypes: dev/smoke_test_builder/dataset/generated/genotypes.tsv
  annotations: dev/smoke_test_builder/dataset/annotations.tsv
  chromosomes: dev/smoke_test_builder/dataset/generated/chromosomes.tsv   # required for kasp if polymarker_genomes > 1

snps:
  min_block_length: 450
  min_snp_flank: 50
  repeat_masking:
    library: ".tests/integration/resources/mini_TE_lib.fasta"

kasp:
  polymarker_genomes: 2
  mfeprimer:
    specificity:
      min_tm: 50
    dimer:
      max_dg: -3.5

viewer:
  dotplot_reference: null

advanced:
  sibeliaz:
    extra_options: []
  batching:
    blocks_per_chunk: 2
  alignment:
    mafft_options: []
  mfeprimer:
    specificity_extra_options: []
    dimer_extra_options: []
    hairpin_extra_options: []
