project:
  name: "Integration test"

inputs:
  genotypes: genotypes.tsv
  annotations: null
  chromosomes: null

snps:
  min_block_length: 1
  min_snp_flank: 0
  repeat_masking:
    library: null

kasp:
  polymarker_genomes: 1

viewer:
  dotplot_reference: null

advanced:
  sibeliaz:
    extra_options: []

  batching:
    blocks_per_chunk: 1

  alignment:
    mafft_options: []
    
  mfeprimer:
    kmer_size: 9
    specificity_extra_options: []
    dimer_extra_options: []
    hairpin_extra_options: []
